name: swift-algorithms ci
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '45 2,13 * * *'
jobs:
  test:
    # emulator fails to launch with: HVF error: HV_UNSUPPORTED
    #runs-on: macos-15
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package on Linux"
        run: |
          brew install docker colima
          colima start
          docker run --rm -v "$PWD":/host -w /host swift:6.0.1 swift test
      - name: "Test Swift Package Locally"
        run: swift test
      - name: "Test Swift (5.10) Package on Android"
        uses: skiptools/swift-android-action@v1
        with:
          swift-version: '5.10'
      - name: "Cleanup build"
        run: rm -rf .build
      - name: "Test Swift (6.0) Package on Android"
        uses: skiptools/swift-android-action@v1
        with:
          swift-version: '6.0'
          #android-emulator-arch: 'arm64-v8a'
      - name: "Test Swift Package on iOS"
        run: xcodebuild test -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 15" -scheme "$(xcodebuild -list -json | jq -r '.workspace.schemes[-1]')"

