name: swift-github-workflows
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '45 6,19 * * *'

jobs:
  tests:
    name: swiftlang/github-workflows tests
    #uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    # use the fork until https://github.com/swiftlang/github-workflows/issues/83
    uses: skiptools/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_linux_checks: true
      enable_windows_checks: true
      enable_android_checks: true

